namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of AddComment
    /// </summary>
    public class AddCommentPayload : QueryableValue<AddCommentPayload>
    {
        internal AddCommentPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The edge from the subject's comment connection.
        /// </summary>
        public IssueCommentEdge CommentEdge => this.CreateProperty(x => x.CommentEdge, Octokit.Model.IssueCommentEdge.Create);

        /// <summary>
        /// The subject
        /// </summary>
        public INode Subject => this.CreateProperty(x => x.Subject, Octokit.Model.Internal.StubINode.Create);

        /// <summary>
        /// The edge from the subject's timeline connection.
        /// </summary>
        public IssueTimelineItemEdge TimelineEdge => this.CreateProperty(x => x.TimelineEdge, Octokit.Model.IssueTimelineItemEdge.Create);

        internal static AddCommentPayload Create(Expression expression)
        {
            return new AddCommentPayload(expression);
        }
    }
}