namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of AddEnterpriseOrganizationMember
    /// </summary>
    public class AddEnterpriseOrganizationMemberPayload : QueryableValue<AddEnterpriseOrganizationMemberPayload>
    {
        internal AddEnterpriseOrganizationMemberPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The users who were added to the organization.
        /// </summary>
        public IQueryableList<User> Users => this.CreateProperty(x => x.Users);

        internal static AddEnterpriseOrganizationMemberPayload Create(Expression expression)
        {
            return new AddEnterpriseOrganizationMemberPayload(expression);
        }
    }
}