namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of AddReaction
    /// </summary>
    public class AddReactionPayload : QueryableValue<AddReactionPayload>
    {
        internal AddReactionPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The reaction object.
        /// </summary>
        public Reaction Reaction => this.CreateProperty(x => x.Reaction, Octokit.Model.Reaction.Create);

        /// <summary>
        /// The reaction groups for the subject.
        /// </summary>
        public IQueryableList<ReactionGroup> ReactionGroups => this.CreateProperty(x => x.ReactionGroups);

        /// <summary>
        /// The reactable subject.
        /// </summary>
        public IReactable Subject => this.CreateProperty(x => x.Subject, Octokit.Model.Internal.StubIReactable.Create);

        internal static AddReactionPayload Create(Expression expression)
        {
            return new AddReactionPayload(expression);
        }
    }
}