namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of ArchiveProjectV2Item
    /// </summary>
    public class ArchiveProjectV2ItemPayload : QueryableValue<ArchiveProjectV2ItemPayload>
    {
        internal ArchiveProjectV2ItemPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The item archived from the project.
        /// </summary>
        public ProjectV2Item Item => this.CreateProperty(x => x.Item, Octokit.Model.ProjectV2Item.Create);

        internal static ArchiveProjectV2ItemPayload Create(Expression expression)
        {
            return new ArchiveProjectV2ItemPayload(expression);
        }
    }
}