namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of CloneProject
    /// </summary>
    public class CloneProjectPayload : QueryableValue<CloneProjectPayload>
    {
        internal CloneProjectPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The id of the JobStatus for populating cloned fields.
        /// </summary>
        public string JobStatusId { get; }

        /// <summary>
        /// The new cloned project.
        /// </summary>
        public Project Project => this.CreateProperty(x => x.Project, Octokit.Model.Project.Create);

        internal static CloneProjectPayload Create(Expression expression)
        {
            return new CloneProjectPayload(expression);
        }
    }
}