namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of CloseDiscussion
    /// </summary>
    public class CloseDiscussionPayload : QueryableValue<CloseDiscussionPayload>
    {
        internal CloseDiscussionPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The discussion that was closed.
        /// </summary>
        public Discussion Discussion => this.CreateProperty(x => x.Discussion, Octokit.Model.Discussion.Create);

        internal static CloseDiscussionPayload Create(Expression expression)
        {
            return new CloseDiscussionPayload(expression);
        }
    }
}