namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of CloseIssue
    /// </summary>
    public class CloseIssuePayload : QueryableValue<CloseIssuePayload>
    {
        internal CloseIssuePayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The issue that was closed.
        /// </summary>
        public Issue Issue => this.CreateProperty(x => x.Issue, Octokit.Model.Issue.Create);

        internal static CloseIssuePayload Create(Expression expression)
        {
            return new CloseIssuePayload(expression);
        }
    }
}