namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of CreateEnvironment
    /// </summary>
    public class CreateEnvironmentPayload : QueryableValue<CreateEnvironmentPayload>
    {
        internal CreateEnvironmentPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The new or existing environment.
        /// </summary>
        public Environment Environment => this.CreateProperty(x => x.Environment, Octokit.Model.Environment.Create);

        internal static CreateEnvironmentPayload Create(Expression expression)
        {
            return new CreateEnvironmentPayload(expression);
        }
    }
}