namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of CreateSponsorship
    /// </summary>
    public class CreateSponsorshipPayload : QueryableValue<CreateSponsorshipPayload>
    {
        internal CreateSponsorshipPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The sponsorship that was started.
        /// </summary>
        public Sponsorship Sponsorship => this.CreateProperty(x => x.Sponsorship, Octokit.Model.Sponsorship.Create);

        internal static CreateSponsorshipPayload Create(Expression expression)
        {
            return new CreateSponsorshipPayload(expression);
        }
    }
}