namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of CreateIssue
    /// </summary>
    public class CreateIssuePayload : QueryableValue<CreateIssuePayload>
    {
        internal CreateIssuePayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The new issue.
        /// </summary>
        public Issue Issue => this.CreateProperty(x => x.Issue, Octokit.Model.Issue.Create);

        internal static CreateIssuePayload Create(Expression expression)
        {
            return new CreateIssuePayload(expression);
        }
    }
}