namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of DeleteDiscussion
    /// </summary>
    public class DeleteDiscussionPayload : QueryableValue<DeleteDiscussionPayload>
    {
        internal DeleteDiscussionPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The discussion that was just deleted.
        /// </summary>
        public Discussion Discussion => this.CreateProperty(x => x.Discussion, Octokit.Model.Discussion.Create);

        internal static DeleteDiscussionPayload Create(Expression expression)
        {
            return new DeleteDiscussionPayload(expression);
        }
    }
}