namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of DeleteEnvironment
    /// </summary>
    public class DeleteEnvironmentPayload : QueryableValue<DeleteEnvironmentPayload>
    {
        internal DeleteEnvironmentPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        internal static DeleteEnvironmentPayload Create(Expression expression)
        {
            return new DeleteEnvironmentPayload(expression);
        }
    }
}