namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of DeleteLinkedBranch
    /// </summary>
    public class DeleteLinkedBranchPayload : QueryableValue<DeleteLinkedBranchPayload>
    {
        internal DeleteLinkedBranchPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The issue the linked branch was unlinked from.
        /// </summary>
        public Issue Issue => this.CreateProperty(x => x.Issue, Octokit.Model.Issue.Create);

        internal static DeleteLinkedBranchPayload Create(Expression expression)
        {
            return new DeleteLinkedBranchPayload(expression);
        }
    }
}