namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of DequeuePullRequest
    /// </summary>
    public class DequeuePullRequestPayload : QueryableValue<DequeuePullRequestPayload>
    {
        internal DequeuePullRequestPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The merge queue entry of the dequeued pull request.
        /// </summary>
        public MergeQueueEntry MergeQueueEntry => this.CreateProperty(x => x.MergeQueueEntry, Octokit.Model.MergeQueueEntry.Create);

        internal static DequeuePullRequestPayload Create(Expression expression)
        {
            return new DequeuePullRequestPayload(expression);
        }
    }
}