namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of EnqueuePullRequest
    /// </summary>
    public class EnqueuePullRequestPayload : QueryableValue<EnqueuePullRequestPayload>
    {
        internal EnqueuePullRequestPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The merge queue entry for the enqueued pull request.
        /// </summary>
        public MergeQueueEntry MergeQueueEntry => this.CreateProperty(x => x.MergeQueueEntry, Octokit.Model.MergeQueueEntry.Create);

        internal static EnqueuePullRequestPayload Create(Expression expression)
        {
            return new EnqueuePullRequestPayload(expression);
        }
    }
}