namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of LinkProjectV2ToTeam
    /// </summary>
    public class LinkProjectV2ToTeamPayload : QueryableValue<LinkProjectV2ToTeamPayload>
    {
        internal LinkProjectV2ToTeamPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The team the project is linked to
        /// </summary>
        public Team Team => this.CreateProperty(x => x.Team, Octokit.Model.Team.Create);

        internal static LinkProjectV2ToTeamPayload Create(Expression expression)
        {
            return new LinkProjectV2ToTeamPayload(expression);
        }
    }
}