namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of RemoveUpvote
    /// </summary>
    public class RemoveUpvotePayload : QueryableValue<RemoveUpvotePayload>
    {
        internal RemoveUpvotePayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The votable subject.
        /// </summary>
        public IVotable Subject => this.CreateProperty(x => x.Subject, Octokit.Model.Internal.StubIVotable.Create);

        internal static RemoveUpvotePayload Create(Expression expression)
        {
            return new RemoveUpvotePayload(expression);
        }
    }
}