namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of ResolveReviewThread
    /// </summary>
    public class ResolveReviewThreadPayload : QueryableValue<ResolveReviewThreadPayload>
    {
        internal ResolveReviewThreadPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The thread to resolve.
        /// </summary>
        public PullRequestReviewThread Thread => this.CreateProperty(x => x.Thread, Octokit.Model.PullRequestReviewThread.Create);

        internal static ResolveReviewThreadPayload Create(Expression expression)
        {
            return new ResolveReviewThreadPayload(expression);
        }
    }
}