namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of RevertPullRequest
    /// </summary>
    public class RevertPullRequestPayload : QueryableValue<RevertPullRequestPayload>
    {
        internal RevertPullRequestPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The pull request that was reverted.
        /// </summary>
        public PullRequest PullRequest => this.CreateProperty(x => x.PullRequest, Octokit.Model.PullRequest.Create);

        /// <summary>
        /// The new pull request that reverts the input pull request.
        /// </summary>
        public PullRequest RevertPullRequest => this.CreateProperty(x => x.RevertPullRequest, Octokit.Model.PullRequest.Create);

        internal static RevertPullRequestPayload Create(Expression expression)
        {
            return new RevertPullRequestPayload(expression);
        }
    }
}