namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of StartOrganizationMigration
    /// </summary>
    public class StartOrganizationMigrationPayload : QueryableValue<StartOrganizationMigrationPayload>
    {
        internal StartOrganizationMigrationPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The new organization migration.
        /// </summary>
        public OrganizationMigration OrgMigration => this.CreateProperty(x => x.OrgMigration, Octokit.Model.OrganizationMigration.Create);

        internal static StartOrganizationMigrationPayload Create(Expression expression)
        {
            return new StartOrganizationMigrationPayload(expression);
        }
    }
}