namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdateIpAllowListForInstalledAppsEnabledSetting
    /// </summary>
    public class UpdateIpAllowListForInstalledAppsEnabledSettingPayload : QueryableValue<UpdateIpAllowListForInstalledAppsEnabledSettingPayload>
    {
        internal UpdateIpAllowListForInstalledAppsEnabledSettingPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The IP allow list owner on which the setting was updated.
        /// </summary>
        public IpAllowListOwner Owner => this.CreateProperty(x => x.Owner, Octokit.Model.IpAllowListOwner.Create);

        internal static UpdateIpAllowListForInstalledAppsEnabledSettingPayload Create(Expression expression)
        {
            return new UpdateIpAllowListForInstalledAppsEnabledSettingPayload(expression);
        }
    }
}