namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdateProject
    /// </summary>
    public class UpdateProjectPayload : QueryableValue<UpdateProjectPayload>
    {
        internal UpdateProjectPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The updated project.
        /// </summary>
        public Project Project => this.CreateProperty(x => x.Project, Octokit.Model.Project.Create);

        internal static UpdateProjectPayload Create(Expression expression)
        {
            return new UpdateProjectPayload(expression);
        }
    }
}