namespace Octokit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.Core;
    using Octokit.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdateRepositoryRuleset
    /// </summary>
    public class UpdateRepositoryRulesetPayload : QueryableValue<UpdateRepositoryRulesetPayload>
    {
        internal UpdateRepositoryRulesetPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The newly created Ruleset.
        /// </summary>
        public RepositoryRuleset Ruleset => this.CreateProperty(x => x.Ruleset, Octokit.Model.RepositoryRuleset.Create);

        internal static UpdateRepositoryRulesetPayload Create(Expression expression)
        {
            return new UpdateRepositoryRulesetPayload(expression);
        }
    }
}